<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11"/>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11"/>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Identity.Application\Identity.Application.csproj" />
		<ProjectReference Include="..\Identity.Domain\Identity.Domain.csproj" />
		<ProjectReference Include="..\..\..\Shared\HMS.Shared.Abstractions\HMS.Shared.Abstractions.csproj" />
		<ProjectReference Include="..\..\..\Shared\HMS.Shared.Contracts\HMS.Shared.Contracts.csproj" />
		<ProjectReference Include="..\..\..\Shared\HMS.Shared.Outbox\HMS.Shared.Outbox.csproj" />
		<ProjectReference Include="..\..\..\Shared\HMS.Shared.Messaging\HMS.Shared.Messaging.csproj" />
		<ProjectReference Include="..\..\..\Shared\HMS.Shared.Security\HMS.Shared.Security.csproj" />
	</ItemGroup>
</Project>
